"""fastcharts — an experimental Python charting engine.

Cost scales with pixels on screen, not points in the dataset: native Rust core
in the Python process, offset-encoded f32 binary transport, M4 decimation, GPU
density aggregation, and a WebGL2 render client. See docs/design-dossier.md.

Two APIs over one engine:

- **Fluent** (`Figure().scatter(...).line(...)`) — quick and imperative.
- **Composition** (Reflex-flavored) — declarative, `on_*` event props:

      import fastcharts as fc
      fc.scatter_chart(
          fc.scatter(x="gdp", y="life", color="continent", size="pop", data=df),
          fc.x_axis(label="GDP"), fc.y_axis(label="life expectancy"),
          fc.legend(),
          on_select=lambda sel: print(len(sel), "points"),
      )

Import does no heavy work (§33 import-time budget). Public symbols below are
exported lazily so `import fastcharts` does not import NumPy or dlopen the
native core; those initialize when a chart-building API is first imported/used.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

__version__ = "0.1.0"

_EXPORTS = {
    "Annotation": ".components",
    "Axis": ".components",
    "CHART_DOM_SLOTS": ".dom",
    "Chart": ".components",
    "Column": ".columns",
    "ColumnStore": ".columns",
    "Component": ".components",
    "Figure": ".figure",
    "Interaction": ".components",
    "Legend": ".components",
    "Mark": ".components",
    "MarkStyle": ".components",
    "Modebar": ".components",
    "Selection": ".figure",
    "Theme": ".components",
    "Tooltip": ".components",
    "ZoneMaps": ".columns",
    "area": ".components",
    "area_chart": ".components",
    "arrow": ".components",
    "bar": ".components",
    "bar_chart": ".components",
    "callout": ".components",
    "candlestick": ".components",
    "candlestick_chart": ".components",
    "chart": ".components",
    "column": ".components",
    "column_chart": ".components",
    "FinanceChart": ".finance",
    "FinanceLayer": ".finance",
    "FinanceTools": ".finance",
    "Instrument": ".finance",
    "Layer": ".finance",
    "PositionDrawing": ".finance",
    "abcd_pattern": ".finance",
    "anchored_volume_profile": ".finance",
    "anchored_vwap": ".finance",
    "anchored_vwap_values": ".finance",
    "bars_pattern": ".finance",
    "bollinger_bands": ".finance",
    "bollinger_bands_values": ".finance",
    "date_price_range": ".finance",
    "date_range": ".finance",
    "drawdown_values": ".finance",
    "equity_curve_values": ".finance",
    "equity_drawdown": ".finance",
    "finance_chart": ".finance",
    "finance_tools": ".finance",
    "fixed_range_volume_profile": ".finance",
    "ghost_feed": ".finance",
    "heatmap": ".components",
    "heatmap_chart": ".components",
    "hline": ".components",
    "hist": ".components",
    "histogram": ".components",
    "histogram_chart": ".components",
    "instrument": ".finance",
    "interaction_config": ".components",
    "label": ".components",
    "legend": ".components",
    "line": ".components",
    "line_chart": ".components",
    "long_position": ".finance",
    "macd": ".finance",
    "macd_values": ".finance",
    "mark_style": ".components",
    "marker": ".components",
    "modebar": ".components",
    "moving_average": ".finance",
    "moving_average_values": ".finance",
    "ohlc": ".components",
    "ohlc_chart": ".components",
    "performance_chart": ".finance",
    "position_forecast": ".finance",
    "price_range": ".finance",
    "returns_distribution": ".finance",
    "returns_distribution_chart": ".finance",
    "returns_distribution_values": ".finance",
    "returns_values": ".finance",
    "rsi": ".finance",
    "rsi_values": ".finance",
    "scatter": ".components",
    "scatter_chart": ".components",
    "sector": ".finance",
    "short_position": ".finance",
    "stochastic": ".finance",
    "stochastic_values": ".finance",
    "text": ".components",
    "theme": ".components",
    "threshold": ".components",
    "threshold_zone": ".components",
    "tooltip": ".components",
    "var_cvar_values": ".finance",
    "vline": ".components",
    "volume_bars": ".finance",
    "volume_profile_values": ".finance",
    "vwap": ".finance",
    "vwap_values": ".finance",
    "x_axis": ".components",
    "x_band": ".components",
    "xabcd_pattern": ".finance",
    "y_band": ".components",
    "y_axis": ".components",
}

__all__ = [
    "CHART_DOM_SLOTS",
    "Annotation",
    "Axis",
    "Chart",
    "Column",
    "ColumnStore",
    "Component",
    "Figure",
    "FinanceChart",
    "FinanceLayer",
    "FinanceTools",
    "Instrument",
    "Interaction",
    "Layer",
    "Legend",
    "Mark",
    "MarkStyle",
    "Modebar",
    "PositionDrawing",
    "Selection",
    "Theme",
    "Tooltip",
    "ZoneMaps",
    "__version__",
    "abcd_pattern",
    "anchored_volume_profile",
    "anchored_vwap",
    "anchored_vwap_values",
    "area",
    "area_chart",
    "arrow",
    "bar",
    "bar_chart",
    "bars_pattern",
    "bollinger_bands",
    "bollinger_bands_values",
    "callout",
    "candlestick",
    "candlestick_chart",
    "chart",
    "column",
    "column_chart",
    "date_price_range",
    "date_range",
    "drawdown_values",
    "equity_curve_values",
    "equity_drawdown",
    "finance_chart",
    "finance_tools",
    "fixed_range_volume_profile",
    "ghost_feed",
    "heatmap",
    "heatmap_chart",
    "hist",
    "histogram",
    "histogram_chart",
    "hline",
    "instrument",
    "interaction_config",
    "label",
    "legend",
    "line",
    "line_chart",
    "long_position",
    "macd",
    "macd_values",
    "mark_style",
    "marker",
    "modebar",
    "moving_average",
    "moving_average_values",
    "ohlc",
    "ohlc_chart",
    "performance_chart",
    "position_forecast",
    "price_range",
    "returns_distribution",
    "returns_distribution_chart",
    "returns_distribution_values",
    "returns_values",
    "rsi",
    "rsi_values",
    "scatter",
    "scatter_chart",
    "sector",
    "short_position",
    "stochastic",
    "stochastic_values",
    "text",
    "theme",
    "threshold",
    "threshold_zone",
    "tooltip",
    "var_cvar_values",
    "vline",
    "volume_bars",
    "volume_profile_values",
    "vwap",
    "vwap_values",
    "x_axis",
    "x_band",
    "xabcd_pattern",
    "y_axis",
    "y_band",
]


def _load_export(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __getattr__(name: str) -> Any:
    return _load_export(name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


if TYPE_CHECKING:
    from .columns import Column, ColumnStore, ZoneMaps
    from .components import (
        Annotation,
        Axis,
        Chart,
        Component,
        Interaction,
        Legend,
        Mark,
        MarkStyle,
        Modebar,
        Theme,
        Tooltip,
        area,
        area_chart,
        arrow,
        bar,
        bar_chart,
        callout,
        candlestick,
        candlestick_chart,
        chart,
        column,
        column_chart,
        heatmap,
        heatmap_chart,
        hist,
        histogram,
        histogram_chart,
        hline,
        interaction_config,
        label,
        legend,
        line,
        line_chart,
        mark_style,
        marker,
        modebar,
        ohlc,
        ohlc_chart,
        scatter,
        scatter_chart,
        text,
        theme,
        threshold,
        threshold_zone,
        tooltip,
        vline,
        x_axis,
        x_band,
        y_axis,
        y_band,
    )
    from .dom import CHART_DOM_SLOTS
    from .figure import Figure, Selection
    from .finance import (
        FinanceChart,
        FinanceLayer,
        FinanceTools,
        Instrument,
        Layer,
        PositionDrawing,
        abcd_pattern,
        anchored_volume_profile,
        anchored_vwap,
        anchored_vwap_values,
        bars_pattern,
        bollinger_bands,
        bollinger_bands_values,
        date_price_range,
        date_range,
        drawdown_values,
        equity_curve_values,
        equity_drawdown,
        finance_chart,
        finance_tools,
        fixed_range_volume_profile,
        ghost_feed,
        instrument,
        long_position,
        macd,
        macd_values,
        moving_average,
        moving_average_values,
        performance_chart,
        position_forecast,
        price_range,
        returns_distribution,
        returns_distribution_chart,
        returns_distribution_values,
        returns_values,
        rsi,
        rsi_values,
        sector,
        short_position,
        stochastic,
        stochastic_values,
        var_cvar_values,
        volume_bars,
        volume_profile_values,
        vwap,
        vwap_values,
        xabcd_pattern,
    )
