#!/usr/bin/env python3
"""Generate the Tailwind-core manifest the native cascade resolves.

One generated stylesheet (`python/xy/styling/_tailwind_core.py`) covering the
exactly-specified core utilities: the full default color palette for
`bg-` / `text-` / `border-` (sourced from the real package —
`scripts/tailwind_palette_v3.json` carries the provenance header — never
hand-typed hexes: a wrong brand color is the worst silent failure this
program exists to end), the numeric spacing scale as padding utilities, the
type scale, font weights and styles, border radii and widths, and letter
tracking. Every value is the published Tailwind default, expressed in
rem/em/px exactly as Tailwind documents it — the cascade resolves rem/em
against its font-size cascade, so the manifest stays faithful rather than
pre-baked.

Utilities OUTSIDE this manifest are simply absent from the stylesheet: the
cascade then reports the unmatched class through its `unsupported` path via
the preflight, which is the §28-honest boundary (a project's full Tailwind
build rides the `stylesheets=` input instead).

    uv run python scripts/gen_tailwind_core.py --write
    uv run python scripts/gen_tailwind_core.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PALETTE = ROOT / "scripts" / "tailwind_palette_v3.json"
TARGET = ROOT / "python" / "xy" / "styling" / "_tailwind_core.py"

VERSION = "core-v1"

#: Tailwind's documented numeric spacing scale (rem = key / 4).
SPACING = [
    "0",
    "0.5",
    "1",
    "1.5",
    "2",
    "2.5",
    "3",
    "3.5",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "14",
    "16",
    "20",
    "24",
]

FONT_SIZES = {
    "xs": ("0.75rem", "1rem"),
    "sm": ("0.875rem", "1.25rem"),
    "base": ("1rem", "1.5rem"),
    "lg": ("1.125rem", "1.75rem"),
    "xl": ("1.25rem", "1.75rem"),
    "2xl": ("1.5rem", "2rem"),
    "3xl": ("1.875rem", "2.25rem"),
    "4xl": ("2.25rem", "2.5rem"),
    "5xl": ("3rem", "1"),
    "6xl": ("3.75rem", "1"),
}

FONT_WEIGHTS = {
    "thin": 100,
    "extralight": 200,
    "light": 300,
    "normal": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700,
    "extrabold": 800,
    "black": 900,
}

RADII = {
    "none": "0px",
    "sm": "2px",
    "": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "2xl": "16px",
    "3xl": "24px",
    "full": "9999px",
}

BORDER_WIDTHS = {"": "1px", "0": "0px", "2": "2px", "4": "4px", "8": "8px"}

TRACKING = {
    "tighter": "-0.05em",
    "tight": "-0.025em",
    "normal": "0em",
    "wide": "0.025em",
    "wider": "0.05em",
    "widest": "0.1em",
}


def _class(name: str) -> str:
    return name.replace(".", "\\.")


def render_css(palette: dict) -> str:
    rules: list[str] = []
    colors: dict[str, str] = {"white": "#fff", "black": "#000"}
    for hue, shades in palette["colors"].items():
        if isinstance(shades, str):
            colors[hue] = shades
            continue
        for shade, value in shades.items():
            colors[f"{hue}-{shade}"] = value
    for name, value in sorted(colors.items()):
        rules.append(f".bg-{_class(name)}{{background-color:{value}}}")
        rules.append(f".text-{_class(name)}{{color:{value}}}")
        rules.append(f".border-{_class(name)}{{border-color:{value}}}")
    rules.append(".bg-transparent{background-color:transparent}")

    for key in SPACING:
        rem = f"{float(key) / 4:g}rem"
        cls = _class(key)
        rules.append(f".p-{cls}{{padding:{rem}}}")
        rules.append(f".px-{cls}{{padding-left:{rem};padding-right:{rem}}}")
        rules.append(f".py-{cls}{{padding-top:{rem};padding-bottom:{rem}}}")
        for side, prop in (("t", "top"), ("r", "right"), ("b", "bottom"), ("l", "left")):
            rules.append(f".p{side}-{cls}{{padding-{prop}:{rem}}}")

    for name, (size, line) in FONT_SIZES.items():
        rules.append(f".text-{name}{{font-size:{size};line-height:{line}}}")
    for name, weight in FONT_WEIGHTS.items():
        rules.append(f".font-{name}{{font-weight:{weight}}}")
    rules.append(".italic{font-style:italic}")
    rules.append(".not-italic{font-style:normal}")
    for name, value in RADII.items():
        cls = f".rounded-{name}" if name else ".rounded"
        rules.append(f"{cls}{{border-radius:{value}}}")
    for name, value in BORDER_WIDTHS.items():
        cls = f".border-{name}" if name else ".border"
        rules.append(f"{cls}{{border-width:{value};border-style:solid}}")
    for name, value in TRACKING.items():
        rules.append(f".tracking-{name}{{letter-spacing:{value}}}")
    return "\n".join(rules)


def render_module(palette: dict) -> str:
    css = render_css(palette)
    return (
        '"""The Tailwind-core manifest, as one generated stylesheet.\n\n'
        "@generated by scripts/gen_tailwind_core.py — do not edit by hand.\n"
        f"Palette provenance: {palette['source']}.\n"
        "The native cascade prepends this sheet when an export names\n"
        f'`tailwind_profile="{VERSION}"`; unmatched utilities are reported by\n'
        "the cascade, never guessed (§28).\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f'TAILWIND_CORE_VERSION = "{VERSION}"\n\n'
        # Emitted as an explicit double-quoted literal (not repr): ruff
        # format normalizes quotes, and a generated file the formatter
        # rewrites is permanently "stale" to --check.
        f'TAILWIND_CORE_CSS = "{_py_string(css)}"\n'
    )


def _py_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    palette = json.loads(PALETTE.read_text(encoding="utf-8"))
    document = render_module(palette)
    if args.write:
        TARGET.write_text(document, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
        return 0
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != document:
            print(f"{TARGET.relative_to(ROOT)} is stale; regenerate with --write", file=sys.stderr)
            return 1
        print("tailwind core manifest is current")
        return 0
    print(document[:2000])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
