#!/usr/bin/env python3
"""Generate `js/src/14_style_snapshot.ts` from `xy.styling.resolved`.

One schema, two languages, zero drift: the Python module is the source of
truth, this script renders the TypeScript mirror, and
`tests/test_resolved_style_snapshot.py` runs `--check` so a committed mirror
that falls behind the schema fails the suite — the same contract
`gen_capability_matrix.py` established for the capability documents.

    uv run python scripts/gen_style_snapshot_types.py --write
    uv run python scripts/gen_style_snapshot_types.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from xy.styling import resolved  # noqa: E402

TARGET = ROOT / "js" / "src" / "14_style_snapshot.ts"


def _const_list(name: str, values: tuple[str, ...]) -> list[str]:
    lines = [f"export const {name} = ["]
    lines += [f'  "{value}",' for value in values]
    lines.append("] as const;")
    return lines


def render() -> str:
    lines = [
        "// @generated by scripts/gen_style_snapshot_types.py — do not edit by hand.",
        "//",
        "// The TypeScript mirror of `python/xy/styling/resolved.py` (schema "
        f"v{resolved.STYLE_SNAPSHOT_VERSION}).",
        "// Concrete values only: no var()/calc(), no relative units — the Python",
        "// side rejects them at construction and the capture side must never",
        "// produce them. Wire shape: spec/design/wire-protocol.md §8.",
        "",
        f"export const STYLE_SNAPSHOT_VERSION = {resolved.STYLE_SNAPSHOT_VERSION} as const;",
        "",
    ]
    lines += _const_list("STYLE_SNAPSHOT_PAINT_PROPERTIES", resolved.PAINT_PROPERTIES_V1)
    lines.append("")
    lines += _const_list("STYLE_SNAPSHOT_TYPOGRAPHY_PROPERTIES", resolved.TYPOGRAPHY_PROPERTIES_V1)
    lines.append("")
    lines += _const_list("STYLE_SNAPSHOT_LAYOUT_PROPERTIES", resolved.LAYOUT_PROPERTIES_V1)
    lines.append("")
    lines += _const_list("STYLE_SNAPSHOT_EFFECT_PROPERTIES", resolved.EFFECT_PROPERTIES_V1)
    lines += [
        "",
        "export const STYLE_SNAPSHOT_PROPERTIES = [",
        "  ...STYLE_SNAPSHOT_PAINT_PROPERTIES,",
        "  ...STYLE_SNAPSHOT_TYPOGRAPHY_PROPERTIES,",
        "  ...STYLE_SNAPSHOT_LAYOUT_PROPERTIES,",
        "  ...STYLE_SNAPSHOT_EFFECT_PROPERTIES,",
        "] as const;",
        "",
        "export type StyleSnapshotProperty = (typeof STYLE_SNAPSHOT_PROPERTIES)[number];",
        "",
        "/** One interned declaration: resolved property -> concrete value. */",
        "export type ResolvedDeclaration = Partial<",
        "  Record<StyleSnapshotProperty, string | number>",
        ">;",
        "",
        "/** One styled slot occurrence; `d` indexes the snapshot's declarations.",
        " * Instance keys are one-letter on the wire because instances are the",
        " * part that repeats with chart density (spec §8). */",
        "export interface StyleSnapshotInstance {",
        "  /** slot name (a `data-xy-slot` value) */",
        "  s: string;",
        "  /** declaration index into `declarations` */",
        "  d: number;",
        '  /** stable identity beyond the slot name, e.g. ["y", "major", "3"] */',
        "  q?: readonly string[];",
        "  /** resolved box in CSS px: [x, y, w, h] */",
        "  g?: readonly [number, number, number, number];",
        "  /** drawn text, when the slot has any */",
        "  c?: string;",
        "}",
        "",
        "export interface StyleSnapshotEnvironment {",
        "  width: number;",
        "  height: number;",
        "  dpr: number;",
        '  color_scheme: "light" | "dark";',
        "}",
        "",
        "export interface ResolvedStyleSnapshot {",
        f"  version: {resolved.STYLE_SNAPSHOT_VERSION};",
        "  style_epoch: number;",
        "  environment: StyleSnapshotEnvironment;",
        "  tokens: Record<string, string | number>;",
        "  states: readonly string[];",
        "  unrepresentable: readonly string[];",
        "  declarations: readonly ResolvedDeclaration[];",
        "  instances: readonly StyleSnapshotInstance[];",
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the committed mirror")
    parser.add_argument("--check", action="store_true", help="fail if the mirror is stale")
    args = parser.parse_args(argv)

    document = render()
    if args.write:
        TARGET.write_text(document, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
        return 0
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != document:
            print(
                f"{TARGET.relative_to(ROOT)} is stale; run "
                "scripts/gen_style_snapshot_types.py --write",
                file=sys.stderr,
            )
            return 1
        print("style snapshot types are current")
        return 0
    print(document)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
