#!/usr/bin/env python3
"""Generate the embedded bitmap font for the native PNG rasterizer.

The Rust core is dependency-free (no FreeType), so `to_png`'s native engine
can't rasterize text at runtime. Instead we bake a small grayscale glyph atlas
here — once, reproducibly — from a bundled TrueType face and emit it as a plain
`const` table into `src/font.rs`. Runtime text is then a coverage blit + bilinear
scale, no font library.

Usage: `uv run python scripts/gen_font.py` (needs Pillow + matplotlib's bundled
DejaVuSans.ttf, both in the `bench`/dev extra). Commit the regenerated
`src/font.rs`.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageFont

# Printable ASCII. Axis labels/titles/legends stay within this set.
FIRST, LAST = 0x20, 0x7E
PX = 16  # render size; runtime scales this coverage bitmap to the requested size.
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "font.rs"


def _load_face() -> ImageFont.FreeTypeFont:
    import matplotlib

    ttf = Path(matplotlib.get_data_path()) / "fonts" / "ttf" / "DejaVuSans.ttf"
    return ImageFont.truetype(str(ttf), PX)


def main() -> None:
    face = _load_face()
    ascent, descent = face.getmetrics()
    cell_h = ascent + descent

    glyphs = []  # (advance, w, h, left, top_from_baseline, coverage bytes)
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        # Advance width (horizontal pen movement).
        advance = round(face.getlength(ch))
        box = face.getbbox(ch)  # (left, top, right, bottom) in the ascent-origin frame
        if box is None or box[2] <= box[0] or box[3] <= box[1]:
            glyphs.append((advance, 0, 0, 0, 0, b""))
            continue
        left, top, right, bottom = box
        w, h = right - left, bottom - top
        img = Image.new("L", (w, h), 0)
        # Draw so the glyph's bbox aligns to (0,0) of `img`.
        from PIL import ImageDraw

        ImageDraw.Draw(img).text((-left, -top), ch, font=face, fill=255)
        # `top` measured downward from the baseline (baseline = ascent).
        top_from_baseline = top - ascent
        glyphs.append((advance, w, h, left, top_from_baseline, img.tobytes()))

    # Flatten coverage into one array with per-glyph offsets.
    blob = bytearray()
    records = []
    for advance, w, h, left, top, cov in glyphs:
        off = len(blob)
        blob.extend(cov)
        records.append((advance, w, h, left, top, off, len(cov)))

    _emit(cell_h, ascent, blob, records)
    print(f"wrote {OUT} — {len(records)} glyphs, {len(blob)} coverage bytes, cell_h={cell_h}")


def _emit(cell_h: int, ascent: int, blob: bytearray, records: list) -> None:
    lines = [
        "// @generated by scripts/gen_font.py — do not edit by hand.",
        "// Grayscale glyph atlas (DejaVu Sans) for the native PNG rasterizer's",
        "// text: the dependency-free Rust core can't run FreeType, so glyph",
        "// coverage is baked here and blitted+scaled at runtime (src/raster.rs).",
        "",
        f"pub const FIRST: u8 = {FIRST};",
        f"pub const LAST: u8 = {LAST};",
        f"pub const BASE_PX: i32 = {PX};",
        f"pub const CELL_H: i32 = {cell_h};",
        f"pub const ASCENT: i32 = {ascent};",
        "",
        "/// Per-glyph metrics at BASE_PX: (advance, w, h, left, top, cov_off, cov_len).",
        "/// `top` is the pixel offset of the glyph's top edge below the baseline",
        "/// (negative = above). Coverage bytes live in `COVERAGE[cov_off..][..cov_len]`,",
        "/// row-major w*h, 0..=255.",
        f"pub static GLYPHS: [(i32, i32, i32, i32, i32, u32, u32); {len(records)}] = [",
    ]
    for advance, w, h, left, top, off, ln in records:
        lines.append(f"    ({advance}, {w}, {h}, {left}, {top}, {off}, {ln}),")
    lines.append("];")
    lines.append("")
    lines.append(f"pub static COVERAGE: [u8; {len(blob)}] = [")
    # 24 bytes per source line.
    for i in range(0, len(blob), 24):
        chunk = ", ".join(str(b) for b in blob[i : i + 24])
        lines.append(f"    {chunk},")
    lines.append("];")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
