"""Advance widths of the core's embedded DejaVu Sans face.

@generated by scripts/gen_font.py — do not edit by hand.

`src/font.rs` bakes the same numbers for the Rust rasterizer that draws the
text; this module is how `_svg.layout()` can size an axis gutter from the ink
it is about to reserve for.  DejaVu Sans is also Matplotlib's default face, so
an advance measured here is the advance Matplotlib would lay out.
"""

from __future__ import annotations

BASE_PX = 16
CELL_H = 19
ASCENT = 15
DESCENT = 4
_FIRST = 32

# fmt: off
# Advances at BASE_PX for the printable ASCII range, `_FIRST` first.
_ASCII: tuple[int, ...] = (
    5, 6, 7, 13, 10, 15, 12, 4, 6, 6, 8, 13, 5, 6, 5, 5, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 5, 5, 13, 13, 13, 8, 16, 11, 11, 11, 12, 10, 9, 12,
    12, 5, 5, 10, 9, 14, 12, 13, 10, 13, 11, 10, 10, 12, 11, 16, 11, 10, 11, 6,
    5, 6, 13, 8, 8, 10, 10, 9, 10, 10, 6, 10, 10, 4, 4, 9, 4, 16, 10, 10,
    10, 10, 7, 8, 6, 10, 9, 13, 9, 9, 8, 10, 5, 10, 13,
)

# Advances at BASE_PX for the non-ASCII glyphs, keyed by codepoint.
_EXTRA: dict[int, int] = {
    176: 8, 177: 13, 178: 6, 179: 6, 181: 10, 183: 5, 185: 6, 215: 13,
    915: 9, 916: 11, 920: 13, 923: 11, 926: 10, 928: 12, 931: 10, 933: 10,
    934: 13, 936: 13, 937: 12, 945: 11, 946: 10, 947: 9, 948: 10, 949: 9,
    950: 9, 951: 10, 952: 10, 953: 5, 954: 9, 955: 9, 956: 10, 957: 9,
    958: 9, 959: 10, 960: 10, 961: 10, 963: 10, 964: 10, 965: 9, 966: 11,
    967: 9, 968: 11, 969: 13, 7522: 3, 7523: 4, 7524: 6, 7525: 7, 8211: 8,
    8212: 16, 8216: 5, 8217: 5, 8220: 8, 8221: 8, 8230: 16, 8304: 6, 8305: 3,
    8308: 6, 8309: 6, 8310: 6, 8311: 6, 8312: 6, 8313: 6, 8314: 8, 8315: 8,
    8316: 8, 8317: 4, 8318: 4, 8319: 6, 8320: 6, 8321: 6, 8322: 6, 8323: 6,
    8324: 6, 8325: 6, 8326: 6, 8327: 6, 8328: 6, 8329: 6, 8330: 8, 8331: 8,
    8332: 8, 8333: 4, 8334: 4, 8336: 6, 8337: 7, 8338: 7, 8339: 7, 8341: 6,
    8342: 7, 8343: 3, 8344: 10, 8345: 6, 8346: 7, 8347: 6, 8348: 5, 8592: 13,
    8594: 13, 8706: 8, 8711: 11, 8712: 14, 8722: 13, 8723: 13, 8730: 10, 8733: 11,
    8734: 13, 8747: 8, 8776: 13, 8800: 13, 8804: 13, 8805: 13,
}
# fmt: on

# Fallback advance for a codepoint the atlas has no glyph for: the
# rasterizer skips it entirely, so it contributes no ink and no advance.
_MISSING = 0


def advance(text: str, font_size: float) -> float:
    """Advance width in px of `text` rendered at `font_size`."""
    units = 0
    for char in text:
        code = ord(char)
        if _FIRST <= code < _FIRST + len(_ASCII):
            units += _ASCII[code - _FIRST]
        else:
            units += _EXTRA.get(code, _MISSING)
    return font_size * units / BASE_PX
